let region = {
    aliyun: [
        {name: '华东 1（杭州）', val: 'oss-cn-hangzhou.aliyuncs.com'},
        {name: '华东 2（上海）', val: 'oss-cn-shanghai.aliyuncs.com'},
        {name: '华北 1（青岛）', val: 'oss-cn-qingdao.aliyuncs.com'},
        {name: '华北 2（北京）', val: 'oss-cn-beijing.aliyuncs.com'},
        {name: '华北 3（张家口）', val: 'oss-cn-zhangjiakou.aliyuncs.com'},
        {name: '华北 5（呼和浩特）', val: 'oss-cn-huhehaote.aliyuncs.com'},
        {name: '华北 6（乌兰察布）', val: 'oss-cn-wulanchabu.aliyuncs.com'},
        {name: '华南 1（深圳）', val: 'oss-cn-shenzhen.aliyuncs.com'},
        {name: '华南 2（河源）', val: 'oss-cn-heyuan.aliyuncs.com'},
        {name: '华南 3（广州）', val: 'oss-cn-guangzhou.aliyuncs.com'},
        {name: '西南 1（成都）', val: 'oss-cn-chengdu.aliyuncs.com'},
        {name: '中国（香港）', val: 'oss-cn-hongkong.aliyuncs.com'},
        {name: '新加坡', val: 'oss-ap-southeast-1.aliyuncs.com'},
        {name: '日本（东京）', val: 'oss-ap-northeast-1.aliyuncs.com'},
        {name: '美国西部 1 （硅谷）', val: 'oss-us-west-1.aliyuncs.com'},
        {name: '美国东部 1 （弗吉尼亚）', val: 'oss-us-east-1.aliyuncs.com'},
        {name: '亚太东南 1 （新加坡）', val: 'oss-ap-southeast-1.aliyuncs.com'},
        {name: '亚太东南 2 （悉尼）', val: 'oss-ap-southeast-2.aliyuncs.com'},
        {name: '亚太东南 3 （吉隆坡）', val: 'oss-ap-southeast-3.aliyuncs.com'},
        {name: '亚太东南 5 （雅加达）', val: 'oss-ap-southeast-5.aliyuncs.com'},
        {name: '亚太东北 1 （日本）', val: 'oss-ap-northeast-1.aliyuncs.com'},
        {name: '亚太南部 1 （孟买）', val: 'oss-ap-south-1.aliyuncs.com'},
        {name: '欧洲中部 1 （法兰克福）', val: 'oss-eu-central-1.aliyuncs.com'},
        {name: '英国（伦敦）', val: 'oss-eu-west-1.aliyuncs.com'},
        {name: '中东东部 1 （迪拜）', val: 'oss-me-east-1.aliyuncs.com'}
    ],
    tencent: [
        {name: '北京一区', val: 'cos.ap-beijing-1.myqcloud.com'},
        {name: '北京', val: 'cos.ap-beijing.myqcloud.com'},
        {name: '上海', val: 'cos.ap-shanghai.myqcloud.com'},
        {name: '广州', val: 'cos.ap-guangzhou.myqcloud.com'},
        {name: '成都', val: 'cos.ap-chengdu.myqcloud.com'},
        {name: '重庆', val: 'cos.ap-chongqing.myqcloud.com'},
        {name: '深圳金融', val: 'cos.ap-shenzhen-fsi.myqcloud.com'},
        {name: '上海金融', val: 'cos.ap-shanghai-fsi.myqcloud.com'},
        {name: '北京金融', val: 'cos.ap-beijing-fsi.myqcloud.com'},
        {name: '中国香港', val: 'cos.ap-hongkong.myqcloud.com'},
        {name: '新加坡', val: 'cos.ap-singapore.myqcloud.com'},
        {name: '孟买', val: 'cos.ap-mumbai.myqcloud.com'},
        {name: '雅达加', val: 'cos.ap-jakarta.myqcloud.com'},
        {name: '首尔', val: 'cos.ap-seoul.myqcloud.com'},
        {name: '曼谷', val: 'cos.ap-bangkok.myqcloud.com'},
        {name: '东京', val: 'cos.ap-tokyo.myqcloud.com'},
        {name: '硅谷（美西）', val: 'cos.na-siliconvalley.myqcloud.com'},
        {name: '弗吉尼亚（美东）', val: 'cos.na-ashburn.myqcloud.com'},
        {name: '多伦多', val: 'cos.na-toronto.myqcloud.com'},
        {name: '法兰克福', val: 'cos.eu-frankfurt.myqcloud.com'},
        {name: '莫斯科', val: 'cos.eu-moscow'}
    ],
    huawei: [
        {name: '非洲-约翰内斯堡', val: 'obs.af-south-1.myhuaweicloud.com'},
        {name: '华北-北京四', val: 'obs.cn-north-4.myhuaweicloud.com'},
        {name: '华北-北京一', val: 'obs.cn-north-1.myhuaweicloud.com'},
        {name: '华东-上海二', val: 'obs.cn-east-2.myhuaweicloud.com'},
        {name: '华东-上海一', val: 'obs.cn-east-3.myhuaweicloud.com'},
        {name: '华南-广州', val: 'obs.cn-south-1.myhuaweicloud.com'},
        {name: '西南-贵阳一', val: 'obs.cn-southwest-2.myhuaweicloud.com'},
        {name: '亚太-曼谷', val: 'obs.ap-southeast-2.myhuaweicloud.com'},
        {name: '中国-香港', val: 'obs.ap-southeast-1.myhuaweicloud.com'},
        {name: '亚太-新加坡', val: 'obs.ap-southeast-3.myhuaweicloud.com'}
    ],
    qiniu: [
        {name: '华东', val: 's3-cn-east-1.qiniucs.com'},
        {name: '华北', val: 's3-cn-north-1.qiniucs.com'},
        {name: '华南', val: 's3-cn-south-1.qiniucs.com'},
        {name: '北美', val: 's3-us-north-1.qiniucs.com'},
        {name: '东南亚', val: 's3-ap-southeast-1.qiniucs.com'},
        {name: '华东-浙江2', val: 's3-cn-east-2.qiniucs.com'}
    ]
};

export default region;
